[build]
  command = """
    rustup toolchain install nightly-2025-08-05-x86_64-unknown-linux-gnu --allow-downgrade --profile minimal &&
    rustup component add rust-src --toolchain nightly-2025-08-05-x86_64-unknown-linux-gnu &&
    rustup target add wasm32-unknown-unknown --toolchain nightly-2025-08-05-x86_64-unknown-linux-gnu &&
    export RUSTUP_TOOLCHAIN=nightly-2025-08-05-x86_64-unknown-linux-gnu &&
    rustc --version --verbose || true &&
    rustup show || true &&
    npm run build
  """
  publish = "dist"

[build.environment]
  RUSTUP_TOOLCHAIN = "nightly-2025-08-05-x86_64-unknown-linux-gnu"

[[headers]]
  for = "/*"
  [headers.values]
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Embedder-Policy = "require-corp"