[build]
  command = "rustup component add rust-src --toolchain nightly-2025-07-19-x86_64-unknown-linux-gnu && npm run build"
  publish = "dist"

[build.environment]
  RUSTUP_TOOLCHAIN = "nightly-2025-07-19-x86_64-unknown-linux-gnu"

[[headers]]
  for = "/*"
  [headers.values]
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Embedder-Policy = "require-corp"